#import "template.typ": ieee
#import "@preview/wordometer:0.1.5": total-words, word-count

#show: word-count

#show: ieee.with(
  title: "The LL(1) Parsing Algorithm",
  authors: (
    (
      name: "Student Number: 730002704",
      organization: "ECM3428: Algorithms that Changed the World",
    ),
  ),
  abstract: "This technical report explores the LL(1) parsing algorithm by discussing its principles, complexity, applications, limitations, and implementation. An evaluation of an LLM-generated report is also given.",
  bibliography: bibliography("refs.bib"),
)

_I certify that all material in this report which is not my own work has been identified._
// #text(font: "Lucida Handwriting")[\- KM]

// #pagebreak()

#word-count(total => [
  = The LL(1) Algorithm
  == Introduction
  === Background on Parsing
  A _parser_ is a program that verifies if a series of tokens can be generated by a given grammar. Within a compiler, the tokens will come from a lexical analyzer (which in turn generates the tokens from the text of the source code), and the output of the parser provides some kind of structural information about the source program @aho_compilers_2002.

  The LL(1) parsing algorithm is a _top-down_, predictive parser for _context-free grammars_. In the context of parsers, _top-down_ refers to how the parsing process begins with some start symbol and attempts to rewrite it until it matches the input string. In this way it generates a _parse tree_ that represents the derivation of the input string starting at the root, hence top-down as opposed to some bottom-up parsers that start from the leaves of the parse tree @aho_compilers_2002.

  LL(1) belongs in the family of LL($k$) parsers. LL($k$) is an acronym for _left-to-right scan_, _leftmost derivation_, with $k$ tokens of lookahead. _Left-to-right scan_ means that the parsing occurs by reading input from left to right, and _leftmost derivation_ means that the parser always expands the leftmost nonterminal first. This ensures that the parsing is deterministic. The $k$ indicates how many tokens of lookahead the parser uses to make parsing decisions. For LL(1) the parser has only one token of lookahead, which makes it the most efficient in terms of time and space complexity but limits the class of grammars that can be parsed @rosenkrantz_properties_1970.

  === Grammars
  A grammar is a set of rules, called _productions_, that define how strings in a language can be generated. Each production has left-hand side consisting of a single _nonterminal_ symbol, and a right-hand side consisting of a string of _grammar symbols_ that can be either _terminal_ or nonterminal symbols. Terminal symbols are the basic symbols from which strings are formed (e.g., keywords, operators, identifiers) and nonterminal symbols are placeholders for patterns of terminal symbols that can be further expanded.

  A _context-free grammar_ is a set of rules that define how strings in a language can be generated that do not depend on the context of a nonterminal. A mathematically rigorous definition of context-free grammars is given by Roskenkrantz et al. @rosenkrantz_properties_1970.

  In this report I follow the convention of using lower-case letters (e.g., $a$, $b$) to denote terminal symbols, upper-case letters early in the alphabet (e.g., $A$, $B$) to denote nonterminal symbols, upper-case letters late in the alphabet (e.g., $X$, $Y$) to denote arbitrary grammar symbols (both terminal and nonterminal), and Greek letters (e.g., $alpha$, $beta$) to denote strings of grammar symbols. The symbol $epsilon.alt$ denotes the empty string, and $S$ the start symbol. A generic production is therefore $A arrow.r alpha$. The notation $A arrow.r.double^* alpha$ means that $A$ can derive $alpha$ in zero or more steps @aho_compilers_2002.

  == Principles
  === Overview
  The LL(1) algorithm is a _predictive_ parser. This means that it decides which production to use by looking only at the next input token and the current nonterminal to be expanded. This is in contrast to other parsing methods that may require backtracking or more lookahead tokens.

  The algorithm requires an input buffer, a stack, and a parsing table. The input buffer contains the string to be parsed followed by an end-of-input marker (often denoted by \$). The stack contains a sequence of grammar symbols (terminal or nonterminal), initialised with the start symbol of the grammar followed by the end-of-input marker. The parsing table has a row for each nonterminal in the grammar and a column for each terminal, including \$. Each cell of the table contains either a production rule or an error indication. Exactly how this table is constructed is discussed later @aho_compilers_2002.

  === Algorithm Overview
  The algorithm starts by intialising a stack with $S\$$, with $S$ on top. The input buffer is the string to be parsed followed by $\$$, with the first symbol of the string as the current input token.

  Additionally as input the algorithm takes a parsing table constructed from the grammar to be used. The construction of this table can be convoluted but forms a key part of the algorithm and is explained in the next subsection.

  Let $X$ be the symbol on top of the stack, and $a$ be the current input token. There are three cases to consider:
  + If $X = a = \$$, then the parsing has been completed successfully.
  + If $X = a != \$$, then pop $X$ from the stack and advance the input to the next token.
  + If $X$ is a nonterminal, look up the entry for $(X, a)$ in the parsing table:
    + If the entry is a production $X arrow.r Y_1Y_2...Y_i$, pop $X$ from the stack and push $Y_i, Y_(i-1), ..., Y_1$ onto the stack (with $Y_1$ on top).
    + If the entry is an error, then the input string is not in the language generated by the grammar.
  This process is repeated until either the input is accepted or an error is encountered @aho_compilers_2002.

  === Constructing the Predictive Parsing Table
  The construction of a predictive parsing table for an LL(1) grammar requires two functions: _FIRST_ and _FOLLOW_.

  For any string of grammar symbols $alpha$, let $upright("FIRST")(alpha)$ be the set of terminals that begin the strings derived from $alpha$. If $alpha arrow.r.double^* epsilon.alt$, then $epsilon.alt$ is also in $upright("FIRST")(alpha)$. To compute $upright("FIRST")(X)$ for all symbols in a grammar, the following rules are applied iteratively until no more terminals can be added @aho_compilers_2002:
  + If $X$ is a terminal, then $upright("FIRST")(X) = {X}$.
  + If $X arrow.r epsilon.alt$ is a production, then add $epsilon.alt$ to $upright("FIRST")(X)$.
  + If $X$ is a nonterminal and $X arrow.r Y_1Y_2...Y_k$ is a production:
    + Add $upright("FIRST")(Y_i)$ to $upright("FIRST")(X)$ if $epsilon.alt$ is in all $upright("FIRST")(Y_j)$ for $j < i$. That is, if all previous symbols can derive the empty string, then the first terminal of the current symbol can also be the first terminal of the entire production.
    + If $epsilon.alt$ is in $upright("FIRST")(Y_i)$ for all $i = 1, 2, ..., k$, then add $epsilon.alt$ to $upright("FIRST")(X)$.
  First-sets alone are not sufficient to construct the passing table, we also need follow-sets.

  Let $upright("FOLLOW")(A)$, for some nonterminal $A$, be the set of terminals that can appear immediately to the right of $A$. That is, the set of terminals $a$ such that there exists a derivation $S arrow.r.double^* alpha A a beta$ for some strings $alpha$ and $beta$. If $A$ can be the rightmost symbol in some sentential form, then the end-of-input marker $\$$ is also in $upright("FOLLOW")(A)$. $upright("FOLLOW")(A)$ can be computed using the following rules applied iteratively until no more terminals can be added @aho_compilers_2002:
  + Place $\$$ in $upright("FOLLOW")(S)$, where $S$ is the start symbol.
  + If there is a production $A arrow.r alpha B beta$, add everything in $upright("FIRST")(beta)$ except $epsilon.alt$ to $upright("FOLLOW")(B)$.
  + If there is a production $A arrow.r alpha B$ or $A arrow.r alpha B beta$ with $epsilon.alt$ in $upright("FIRST")(beta)$, then add everything in $upright("FOLLOW")(A)$ to $upright("FOLLOW")(B)$.

  From these two functions we can construct a predictive parsing table for some grammar using the following algorithm @aho_compilers_2002:
  + For each production $A arrow.r alpha$ in the grammar:
    + Add $A arrow.r alpha$ to the table entry for $(A, a)$ for each terminal $a$ in $upright("FIRST")(alpha)$.
    + If $epsilon.alt$ is in $upright("FIRST")(alpha)$, then add $A arrow.r alpha$ to the table entry for $(A, b)$ for each terminal $b$ in $upright("FOLLOW")(A)$. Additionally, if $\$$ is in $upright("FOLLOW")(A)$, add $A arrow.r alpha$ to the table entry for $(A, \$)$.
  + If any entry in the table is empty, mark it as an error.
  A grammar is LL(1) (that is, can be parsed by the LL(1) algorithm) if and only if each cell of the parsing table contains at most one production.

  == Complexity Analysis
  For each token of input, the LL(1) algorithm performs a constant amount of work: it either exits, pops a terminal from the stack and advances the input, or looks up a production in the parsing table and adds symbols to the stack. Therefore, if $n$ is the number of tokens in the input string, the time complexity of the LL(1) algorithm is $O(n)$.

  Calculating the time complexity of constructing the parsing table is more complex. // TODO

  == Applications
  As with many algorithms, the LL(1) parsing algorithm makes a trade-off for effciency. By limiting the class of grammars that can be parsed, the algorithm achieves linear time complexity. Consider syntax highlighting in a text editor. The editor needs to parse the source code as the user types, but it is not essential if the parsing is not perfect for incorrect syntax.

  Other applications are simple languages like configuration files or domain-specific languages (DSLs) like SQL.

  Another advantage of LL(1) parsers is that they can be verified. Lasser et al. @lasser_verified_2020 present a verified LL(1) parser for JSON that is proven to be correct with respect to the JSON specification.

  == Limitations
  The main limitation of the LL(1) parsing algorithm is that it can only handle a subset of context-free grammars. It is therefore not suitable for parsing most complex programming languages like C. Such languages often use a combination of general parsing technqiues and handwritten code to handle ambiguities and context-sensitive constructs. For example, the Rust programming language uses a combination of an LL(3) parser and a custom algorithm to handle ambiguities.

  There are algorithms such as Cocke-Younger-Kasami (CYK) and Earley that can parse any context-free grammar, but they are impractical for real use with a worst case time complexity of $O(n^3)$.

  A good parser should also be robust and provide meaningful error messages, which can be achieved with an LL(1) parser but at the cost of performance.

  Word Count: #total.words
])

= Pseudo Code

= Appendix
_This section was generated entirely by prompting a LLM._
